version: '3.9'
services:
  R-notebook:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: msms
    image: docker.io/amnahsid/msms
    ports:
      - '8888:8888'
    volumes:
      - ~:/home/jovyan/
